apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier
  labels:
    app: courier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: courier
  template:
    metadata:
      labels:
        app: courier
    spec:
      containers:
      - name: courier
        image: ${REGISTRY}/remembot/courier:latest
        ports:
        - containerPort: 3002
        resources:
          limits:
            cpu: "0.3"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
        - name: NODE_ENV
          value: production
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 20 