apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: remembot
spec:
  commonName: api.remem.bot
  secretName: api-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - api.remem.bot
