apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
  namespace: remembot
spec:
  selector:
    app: api
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  type: ClusterIP 