apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
  namespace: remembot
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP
