apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
  namespace: remembot
spec:
  commonName: web.remem.bot
  secretName: web-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - web.remem.bot
