name: Deploy

on:
  # Trigger the workflow on push or pull request events that affect k8s
  # manifests
  push:
    branches:
      - main
    paths:
      - "apps/*/k8s/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Prepare to deploy apps from the monorepo:
  # - Find all apps with changes ink8s directories
  pre-deploy:
    name: Pre-deploy
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set matrix
        id: set-matrix
        run: |
          # Get list of all apps
          APPS=$(find apps -maxdepth 2 -type d -name k8s | sed 's|apps/||g' | sed 's|/k8s||g')

          # Create a matrix object with all apps
          MATRIX_JSON=$(echo '{"app": '"$(echo "$APPS" | jq -R -s -c 'split("\n") | map(select(length > 0))')"'}')

          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
          echo "Matrix: $MATRIX_JSON"

  # Deploy apps from the monorepo:
  # - Set up kubectl
  # - Read the deployment target
  # - Apply all Kubernetes manifests (except target.yaml) for this app
  deploy:
    name: Deploy
    needs: pre-deploy
    # Only run this job if there are apps to deploy
    if: ${{ fromJson(needs.pre-deploy.outputs.matrix).app[0] != null }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.pre-deploy.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Read deployment target
        id: target
        run: |
          TARGET=$(cat apps/${{ matrix.app }}/k8s/target.yaml | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
          echo "target=$TARGET" >> $GITHUB_OUTPUT
          echo "Using deployment target: $TARGET"

      - name: Validate kubeconfig secret exists
        id: validate-kubeconfig-secret
        run: |
          SECRET_NAME="${TARGET}_KUBECONFIG"
          KUBECONFIG="${{ secrets[format('{0}_KUBECONFIG', steps.target.outputs.target)] }}"
          if [ -z "$KUBECONFIG" ]; then
            echo "::error::Required secret '$SECRET_NAME' is not set. Please add this secret to the repository."
            exit 1
          fi
          echo "kubeconfig<<EOF" >> $GITHUB_OUTPUT
          echo "$KUBECONFIG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup k8s configuration
        run: |
          mkdir -p $HOME/.kube
          echo "${{ steps.validate-kubeconfig-secret.outputs.kubeconfig }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy ${{ matrix.app }}
        run: |
          echo "Deploying ${{ matrix.app }}..."

          # Apply all Kubernetes manifests (except target.yaml) for this app
          for file in $(find apps/${{ matrix.app }}/k8s -type f -name "*.yaml" ! -name "target.yaml"); do
            kubectl apply -f "$file"
          done

          echo "${{ matrix.app }} deployed successfully"
