# Standalone workflow that creates a new release when necessary, or else
# triggers a publish of all drifted apps.
#
# This should be the most commonly triggered workflow, as any push to k8s
# configuration, changesets configuration, or Node.js configuration kicks it
# off.

name: Release

on:
  # Triggers this workflow when a push is made to the main branch that tweaks
  # k8s configuration or package.json files.
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: release_${{ github.ref }}

jobs:
  # Create a release pull request or publish changed apps.
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    outputs:
      should_publish: ${{ steps.changesets.outputs.published == 'true' }}
    steps:
      # Checkout the repository code.
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits.
          fetch-depth: 0

      # Install Bun.
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      # Install dependencies (we need this so the Changesets action works).
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Create a release pull request if there are changesets, otherwise trigger
      # a publish.
      - name: Create Release
        id: changesets
        uses: changesets/action@v1
        with:
          # So this is a bit of a hack.
          #
          # changesets/action only creates a release on the repo if you have a
          # publish script that succeeds with the right output. We want the
          # release to be created, but we want to handle publish ourselves with
          # a dedicated workflow.
          publish: bun release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish apps where necessary.
  publish-drifted-apps:
    name: Publish drifted apps
    needs: release
    # Only run this job if there are apps to deploy.
    if: ${{ needs.release.outputs.should_publish == 'true' }}
    uses: ./.github/workflows/publish-drifted-apps.yaml
    secrets: inherit # Necessary for accessing the KUBECONFIG etc.

  # Publish packages where necessary.
  publish-drifted-packages:
    name: Publish drifted packages
    needs: release
    # Only run this job if there are apps to deploy.
    if: ${{ needs.release.outputs.should_publish == 'true' }}
    uses: ./.github/workflows/publish-drifted-packages.yaml
    secrets: inherit # Necessary for accessing the KUBECONFIG etc.
