# Standalone workflow that validates a pull request.
#
# This workflow runs checks on pull requests to ensure code quality and proper change management.
# It specifically validates changes to apps and packages directories.

name: Validate PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/**"
      - "packages/**"

jobs:
  # Ensure that changesets are present when apps or packages are modified.
  check-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Verify that a changeset file exists for the PR.
      - name: Check for Changesets
        id: check-changeset
        run: |
          changeset_files=$(find .changeset -maxdepth 1 -type f -name "*.md" ! -name "README.md")
          if [ -n "$changeset_files" ]; then
            echo "has_changeset=true" >> $GITHUB_OUTPUT
            echo "✅ Changeset found"
          else
            echo "has_changeset=false" >> $GITHUB_OUTPUT
            echo "❌ No changeset found"
          fi

      # Show error message if no changeset is found.
      - name: Show changeset requirement
        if: steps.check-changeset.outputs.has_changeset != 'true'
        run: |
          echo "::error::No changeset found. Please create a changeset by running 'bun changeset' and commit the generated files."
          exit 1

  # Lints, type checks, and tests the project.
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Bun.
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      # Install dependencies so we can run checks.
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Run type checking.
      - name: Check types
        run: bun run check-types

      # Run linting.
      - name: Lint
        run: bun lint

      # Test the project.
      - name: Test
        run: bun test
