# Standalone workflow that validates a pull request.
#
# This workflow runs checks on pull requests to ensure code quality and proper change management.
# It specifically validates changes to apps and packages directories.

name: Validate PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/**"
      - "packages/**"

jobs:
  # Ensure that changesets are present when apps or packages are modified
  check-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Verify that a changeset file exists for the PR.
      - name: Check for Changesets
        id: check-changeset
        run: |
          # Look for files that match the changeset pattern (random string + .md)
          # and contain the required changeset content
          if [ -n "$(find .changeset -maxdepth 1 -type f -name "*.md" ! -name "README.md" -exec grep -l "---" {} \;)" ]; then
            echo "has_changeset=true" >> $GITHUB_OUTPUT
            echo "✅ Changeset found"
          else
            echo "has_changeset=false" >> $GITHUB_OUTPUT
            echo "❌ No changeset found"
          fi

      # Show error message if no changeset is found.
      - name: Show changeset requirement
        if: steps.check-changeset.outputs.has_changeset != 'true'
        run: |
          echo "::error::No changeset found. Please create a changeset by running 'bun changeset' and commit the generated files."
          exit 1

  # This job runs the standard build and test pipeline
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Bun.
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.2.11"

      # Install dependencies so we can run checks.
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Run type checking.
      - name: Check types
        run: bun run check-types

      # Run linting.
      - name: Lint
        run: bun run lint

      # Build the project
      - name: Build
        run: bun run build
